logbook:
  format:
    style: http
  minimum-status: 400
  strategy: body-only-if-status-at-least
  predicate:
    exclude:
      - path: /actuator/health/**

logging:
  level:
    root: warn
    service: info
    org.zalando.logbook: trace

management:
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
    metrics:
      access: read_only
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
    access:
      default: none
      max-permitted: read_only
  server:
    port: 8081

server:
  port: 8080

spring:
  application:
    name: spring-boot-service
  jackson:
    default-property-inclusion: non_null

---
spring.config.activate.on-profile: json-logging

logbook:
  format:
    style: json

logging:
  config: classpath:logback-json.xml
