name: 'CI Build'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - run: chmod +x gradlew
    - run: ./gradlew build --no-build-cache --no-daemon
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: reports
        path: build/reports
